spring:
  application:
    name: openai

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ai/gemma3
        base-url: http://localhost:12434/engines
logging:
  pattern:
    console: '%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n'




